import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'



export default function Home() {
  return (
    <>
      <Head>
        <title>Laboratoire</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <div className='min-h-screen w-full grid place-items-center'>
      <div className='flex flex-col items-center'>
        <h1 className='text-2xl font-black'>Tailwind set up</h1>
        <p>google font variable spread to the tailwind config with next/font module</p>
      </div>
     </div>
    </>
  )
}
